### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by cevich** [lintje/action#2]
[When using this action](https://github.com/containers/netavark/pull/451/files) with `ubuntu-latest`, I'm getting this error:

```
Error: Lintje failed with error: TypeError: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at main (/home/runner/work/_actions/lintje/action/v0.11.1/dist/index.js:69966:41)
```

As a guess, I tried defining `LINTJE_OPTIONS_PATH` pointing at a file with only comments in it.  I also tried several different recent tags of the lintje action, all with the same result.  What other info can I provide that would help?

**Comment by tombruijn** [comment]
Hi there! Thanks for reporting the issue. Looks like the GitHub Action payload for PRs was slightly different. I've fixed this in Lintje action 0.11.2. I hope you give Lintje another try!

**Comment by cevich** [comment]
Thanks for fixing!  Hopefully it will benefit others in the community.

---

(unrelated to this issue)

>  I hope you give Lintje another try!

Unfortunately the main feature I was after was the DCO check.  I found it doesn't flag a missing signature, only a misplaced one (not sure if that was intentional or not).  In any case, the deal-killer for my team is being able to disable some checks via command-line, or options file.  This is required in our automation due to automated tools generating PRs which may not produce 100% conforming outputs, but need to be merged ASAP.  For example, dependabot branch-names & PRs.

Anyway, I appreciate you're efforts on the tool and your quick response fixing the problem.  Thanks :+1:

**Comment by tombruijn** [comment]
> I found it doesn't flag a missing signature, only a misplaced one (not sure if that was intentional or not).

It's intentional at the moment that it only checks if it's in the wrong place, otherwise it's not picked up by some systems. It's not possible to configure Lintje to require it right now, and I don't want to require it by default.

> In any case, the deal-killer for my team is being able to disable some checks via command-line, or options file. This is required in our automation due to tools generating PRs which may not produce 100% conforming outputs, but need to be merged ASAP. For example, dependabot branch-names & PRs.

Lintje does already [ignore commits from bots like dependabot automatically](https://github.com/lintje/lintje/blob/bde811fca62ddaf1270cdcc1b9cc8b48664b6ef4/src/git.rs#L274). At least GitHub bots.

I may add a config file in the future, but it's not in my planning right now.

Thanks for the feedback!

**Comment by cevich** [comment]
Oh neat didn't know that.  Unfortunately, we're using another non-github bot :(
